#Error message

list = [1,2,3]

#print(list[3])
#To continue execution post the error. Comment the above line(Line 5) with hash "#"

#Error Handling

try:
    print(list[3])
except:
    print("Something went wrong")
    